version: "3"

services:
  remix-image:
    container_name: frontend
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    environment:
      PORT: 4200
      NODE_ENV: production
      API_URL: 
    networks:
      - npm
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2GB'
          
networks: 
  npm: 
    external: true
    name: npm
